# Set the target system
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    CMAKE_CROSSCOMPILING
    CMAKE_SYSTEM_PROCESSOR
    CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE
    CMAKE_VS_PRODUCTS
    CMAKE_VS_VERSION_PRERELEASE
    CMAKE_VS_VERSION_RANGE
    VS_INSTALLATION_PATH
    VS_INSTALLATION_VERSION
    VS_PLATFORM_TOOLSET_VERSION
)
set(WIN32 1)
set(MSVC 1)

# Set the compiler to use
set(CMAKE_C_COMPILER cl)
set(CMAKE_CXX_COMPILER cl)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
